### ISSUE TITLE
Plugin disappeared from the plugin list

### ISSUE THREAD

**Issue by coolfarmer** [austinvaness/CameraLCD#5]
Any idea if this plugin will be available again?

**Comment by austinvaness** [comment]
I am not sure, there are a few bugs I want to fix that may take a while.

**Comment by MadJoe1974** [comment]
please fix it.... i love this one so much....

**Comment by Jambozal** [comment]
I would love to see this return, bugs or not.. perhaps just with a warning in description?

**Comment by austinvaness** [comment]
Its back on the list
