### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by doctorspooky** [austinvaness/CameraLCD#6]
It now returns error(s) upon SELauncher launch, due to recent updates.

Here's the log:  [loader.log](https://github.com/austinvaness/CameraLCD/files/11523019/loader.log)

I love having the ability to use cameras via LCD's, since I want to play in first person while flying ships.  As such, all my vessels use this plugin!

**Comment by austinvaness** [comment]
This plugin is already off of the list while I try to fix it. The fact that your able to start the game with it enabled means your not getting updates to any plugins

**Comment by austinvaness** [comment]
Its back on the list
